### ISSUE TITLE
Not able to make this work.

### ISSUE THREAD

**Issue by sheminasalam** [MichaluxPL/Sofar_LSW3#21]
I am getting the following error when I try to run this. Hope someone can help

```
Traceback (most recent call last):
  File "InverterData.py", line 51, in <module>
    os.chdir(os.path.dirname(sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by MichaluxPL** [comment]
Try to change this line to this: os.chdir(os.path.dirname(os.path.abspath(sys.argv[0]))).
Alternatively if You run the script like this: python3 InverterData.py, try to run it like this: ./InverterData.py or python3 ./InverterData.py

**Comment by sheminasalam** [comment]
This worked

> ./InverterData.py or python3 ./InverterData.py
