### ISSUE TITLE
No module named 'libscrc'

### ISSUE THREAD

**Issue by tomaszsa** [MichaluxPL/Sofar_LSW3#22]
./InverterData.py 
Traceback (most recent call last):
  File "./InverterData.py", line 11, in <module>
    import libscrc
ModuleNotFoundError: No module named 'libscrc'

Maybe file requirements.txt with depends packages will be resolve isssue.

**Comment by tomaszsa** [comment]
missing packages:

libscrc
paho-mqtt
influxdb

**Comment by MichaluxPL** [comment]
Info about required modules has been added to README.
