### ISSUE TITLE
Status always reported as "Normal"

### ISSUE THREAD

**Issue by choyrack** [MichaluxPL/Sofar_LSW3#26]
The script does not recognize statuses correctly, it always sends "normal".
For example, at the end of the day, the inverter goes into standby, so the script should send "stand-by".

**Comment by MichaluxPL** [comment]
If the script shows status Normal, it means, inverter reports value 2 for the configured register (default: 0x0000).
Maybe Your inverter reports different value for stand-by - in such a case You'll need to modify corresponding "key" value in SOFARMap.xml. Another possibility is the inverter always reports value 2 until it finally turns off at the end of the day (my does exactly that).
So I'd suggest:
1. Check what value is being reported when inverter is in stand-by mode.
2. If it is not "2", than modify key value for stand-by in SOFARMap.xml.
