### ISSUE TITLE
Uruchomienie integracji w HA

### ISSUE THREAD

**Issue by paku2020** [MichaluxPL/Sofar_LSW3#31]
Dzień dobry,

z góry przepraszam jeśli to jest złe miejsce na tego typu pytanie.
Ale proszę o wyrozumiałość.

Podpowie ktoś mniej więcej krok po kroku jak uruchomić tą integrację w HA?  Mam instalację HA ściągniętą z oficjalnej strony zainstalowaną  na rpi4, mqtt też mam i działa. Jednak nie wiem co dalej zrobić. 
Mogę liczyć na jakąś podpowiedz? Próbowałem uruchomić inne integrację do sofara g3, i jest problem z pobieraniem danych z loggera, więc chciałbym to teraz dobrze zrobić i sprawdzić czy będzie działał. Bo jeśli nie to coś nie tak musi być z moją wersją. Już dwie integracja próbowałem i nie udało się. Działa jedynie pobieranie danych z chmury, ale jednak wolałbym lokalnie.

Pozdrawiam

**Comment by MichaluxPL** [comment]
Ja nie posiadam HA więc nie podpowiem. Sugerowałbym zapytać na wątku na elektrodzie: https://www.elektroda.pl/rtvforum/topic3698233-150.html
