### ISSUE TITLE
where to find register_start and register_end values?

### ISSUE THREAD

**Issue by fnurglewitz** [MichaluxPL/Sofar_LSW3#36]
Hi, I tried the script and it does connect successfully but the register offsets are not correct:

0x0000 - Inverter status: 21
No value in response for register 0x0001
Check register start/end values in config.cfg

How can I infer/find the correct values?

Thanks

edit: 
I found out my inverter is a Sofar HYD-6000 ES which shares register addresses with the 3000:
https://github.com/MichaluxPL/Sofar_LSW3/files/7544510/SofarHYD.ES.ME3000SP.Modbus.protocol.pdf

**Comment by glynnallen1704** [comment]
@fnurglewitz  Did you manage to get the correct config for your Sofar HYD-6000 ES i have the same one and i am struggling to get the correct values on my config file. Would really appreciate it if you could share?
