### ISSUE TITLE
Sofar LSW3 - No value in response for register 0x0001

### ISSUE THREAD

**Issue by philkemp** [MichaluxPL/Sofar_LSW3#38]
Hi,

Thanks for sharing your code for this :) sorry if this is a school boy question... relatively new to python programming.

I'm trying to get the realtime usage statistics out of our Sofar HYD3000-ES inverter via the LSW3 wifi dongle, I've been able to get the hardware information as below:

{
    "Product code": "15kW",             <---- This happens to be incorrect :-/.  it's a 3kW Inverter :-/
    "Serial Number": "SMxxxxxxxxx",
    "Software Version": "V260",
    "Hardware Version": "V100",
    "DSP Version": "V260"
}

But when I try to extract the statistics I'm getting

No value in response for register 0x0001
Check register start/end values in config.cfg.   <--  This is left as the default register_start1=0x0000 & register_end1=0x0027, noted you say you may need to change this to work with other inverters?  is there a way to discover what this should be?

I suspect the issue may actually be with the Data Logger rather than the code :-/ as the Yield and power values are shown as 0.0 kWh (as per image below) despite uploading the correct figures into Solarman :-/   think this is likely a firmware problem but cant locate any firmware downloads.

![image](https://user-images.githubusercontent.com/104511914/165544955-c7eeed6d-6301-487f-86b0-d60d2c50201b.png)

Just wondering if you've seen the 'No value in response for register 0x0001' error before or have experience / any ideas with the HYD range of inverters? before I pursue the lack of yield information issue with Solarman / Sofar.

Many Thanks!

Phil

**Comment by philkemp** [comment]
Don't know if this assists, I enabled verbose=1 in the config.cfg

Connecting to logger... connected successfully !
*** Chunk no:  0
Sent data:  bytearray(b'\xa5\x17\x00\x10E\x00\x00\x98\xc0\xbdh\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x03\x00\x00\x00(E\xd4\x00\x15')
Received data:  b'\xa5\x10\x00\x10\x15\x00V\x98\xc0\xbdh\x02\x01\xed\xe7&\x00\xa4\x19\x00\x00d~Bb\x05\x00M\x15'
0x0000 - Inverter status: 21
No value in response for register 0x0001
Check register start/end values in config.cfg

**Comment by philkemp** [comment]
Apologies, very new to github, have located the closed issues and found the register values for HYD inverters from another post and understand how the results are mapped in the relevant XML files etc...

Unfortunately despite updating the script to use the 0x2xx range I constantly get messages like 'No value in response for register 0x0253' which should contain PV2 voltage so think the logger isn't working correctly locally despite working with Solarman.

I will close the issue and chase Sofar / Solarman for a firmware update for the LSW3 logger.

Thank you

**Comment by glynnallen1704** [comment]
> Apologies, very new to github, have located the closed issues and found the register values for HYD inverters from another post and understand how the results are mapped in the relevant XML files etc...
> 
> Unfortunately despite updating the script to use the 0x2xx range I constantly get messages like 'No value in response for register 0x0253' which should contain PV2 voltage so think the logger isn't working correctly locally despite working with Solarman.
> 
> I will close the issue and chase Sofar / Solarman for a firmware update for the LSW3 logger.
> 
> Thank you

Did you manage to get an updated firmware?
