### ISSUE TITLE
integration in fhem

### ISSUE THREAD

**Issue by Heik80** [MichaluxPL/Sofar_LSW3#42]
Hello, can you briefly explain how I can get an integration into FHEM that retrieves the data regularly or live?  Thanks very much

**Comment by MichaluxPL** [comment]
I don't know FHEM, so I won't be able to help You, although if FHEM can read data from MQTT, I'd suggest going this way :)
Alternatively You can parse script text output and read values this way.

**Comment by Heik80** [comment]
Thanks for the answer.  I'll try over MQTT integrate hoping I get the point.
