### ISSUE TITLE
Wifi logger Protocol

### ISSUE THREAD

**Issue by GusakIurii** [MichaluxPL/Sofar_LSW3#43]
MichaluxPL, thanks for a great start with inverters via Wifi logger.
Would you like to make a similar module for the new G3 series inverters, could you share the WiFi Loggera protocol?
I searched the entire Internet, I can’t find anything ...
Maybe you can send it to the post office if you don’t want to post it for everyone: spenikolaev@gmail.com

**Comment by MichaluxPL** [comment]
Everything I know about WiFI Logger protocol You can find in my script - look at lines 133-143.
Unfortunately I do not own G3 series inverter, so I won't be able to write anything for it :(

**Comment by GusakIurii** [comment]
And if I give access to my inverter and the modbus table, could they register? 
If you are interested, please send me your personal email, I will send all the information

**Comment by rimelis** [comment]
The logger protocol is defined here: https://pysolarmanv5.readthedocs.io/en/latest/solarmanv5_protocol.html#further-reading
G3 series inverter has absolutely different function codes and address ranges. The protocol is pinned in https://github.com/pawsuch/Sofar_G3_LSW3 fork.

**Comment by jochym** [comment]
The function code for reading is 0x03 not 0x04 for G3 inverters (I do not know what it is for other types). After changing this value, I got proper response. I will post my changes for KTLX-G3 inverter when I finish register map.
