### ISSUE TITLE
Maybe a Bug?

### ISSUE THREAD

**Issue by ChristopherZender** [MichaluxPL/Sofar_LSW3#45]
Hi MichaluxPL,

i've been using & testing your scripts for about 6 weeks, I have a Sofar 1100tl-g3. Very strange values have been coming from the inverter for about 4 days, I rather suspect that this problem is with the inverter because the wrong values are already displayed there in the dashboard / status page.

Here are a few pictures of it, the inverter thinks I have already generated 22kwh today or 51kwh yesterday :-)
Which is not possible even in the very best location with 3x400w modules :-)

It is strange that ~ every 2 hours the values on the inverter are increased. (seeing picture from yesterday)

Have you ever seen some of these problems?

![image](https://user-images.githubusercontent.com/44568234/184541506-d3982b63-a56f-4d4e-99f4-15bd5372c5c9.png)
![image](https://user-images.githubusercontent.com/44568234/184541596-bb807f65-6bf0-4d44-9045-0d6c7bff0da2.png)
![image](https://user-images.githubusercontent.com/44568234/184541615-3d3746ff-41a3-428d-889d-1536cfaed067.png)

Yesterday:

![image](https://user-images.githubusercontent.com/44568234/184541723-4c01a09e-3e62-4659-8ba2-0bb9e20dc0ef.png)

**Comment by MichaluxPL** [comment]
Your inverter wifi module's web page seems to give exactly the same values as the script. So if they are wrong, You need to contact module's manufacturer and report this problem.
