### ISSUE TITLE
Manual with holidng registers

### ISSUE THREAD

**Issue by kalwinskidawid** [MichaluxPL/Sofar_LSW3#47]
Hey, 
Is it possible for you to drop here a manual with the addresses of all holding registers? I searched on "elektroda.pl", but there is no overlap between these addresses from the script and their pdf. 
How to identify the protocol version?

**Comment by MichaluxPL** [comment]
I believe I've used this one (it was attached on elektroda.pl):
[SOFARSOLAR ModBus-RTU Communication Protocol.zip](https://github.com/MichaluxPL/Sofar_LSW3/files/9823867/SOFARSOLAR.ModBus-RTU.Communication.Protocol.zip)

**Comment by kalwinskidawid** [comment]
Thank you! Idk how but probably I missed it. 
It's so weird that eg. models HYD.* or G3 have a lot of more registers
