### ISSUE TITLE
MODBUS  addresses

### ISSUE THREAD

**Issue by Witekkq** [MichaluxPL/Sofar_LSW3#48]
Hi, 
I got logger with sn starts with 23xxxxxxx, wondering from where you have obtained the addresses of registres from supported devices?

**Comment by MichaluxPL** [comment]
First of all, registers are specific for a given inverter, not associated with type of a logger.
I've register number for my inverter on elektroda.pl. I'd also suggest to read all issues here (also closed ones) - maybe You'll find some interesting info there :)
