### ISSUE TITLE
binascii.Error: Non-hexadecimal digit found

### ISSUE THREAD

**Issue by mef123** [MichaluxPL/Sofar_LSW3#50]
I'm running invertor Afore with LSW-3 logger.
Here is the error i got:
```
python ./InverterData.py 
Connecting to logger... connected successfully !
Traceback (most recent call last):
  File "/home/xxxx/Sofar_LSW3/./InverterData.py", line 140, in <module>
    businessfield= binascii.unhexlify('0103' + pos_ini + pos_fin) # sin CRC16MODBUS
binascii.Error: Non-hexadecimal digit found
```
Logger Firmware version: LSW3_15_1E03_1.31
Device serial number: 2327xxxxxx

This is the registers definition from Afore:
[AFORE_T4.pdf](https://github.com/MichaluxPL/Sofar_LSW3/files/10663030/AFORE_T4.pdf)

**Comment by MichaluxPL** [comment]
Clearly Your inverter is not compatible with my software :( You do not receive readable data, that's why You get this error.
Unfortunately I won't be able to help with that.
