### ISSUE TITLE
Network settings- only AP mode?

### ISSUE THREAD

**Issue by Dobie007** [MichaluxPL/Sofar_LSW3#51]
Maybe i am missing something obvious:
I can access my Solarmax SGA converter (= SOFAR 1600K TL- G3) with the LSW-3 stick  if i connect to the stick in AP mode, i.e. direct wifi connection to the stick. At the same time the stick has access to my regular wifi network and transmits everything to a server from Solarmanpv. So far so good..

If i connect to my wifi network myself and try to access the stick that way i get a timeout:
"Connecting to logger... Could not open socket - inverter/logger turned off"

My goal is to access the stick out of my normal local wifi network and stop it from sending data elswhere. Is that possible?

(Ser 235xxx, LSW3_15_FFFF_1.0.65, V1.1.00.0B)

**Comment by MichaluxPL** [comment]
Taka a look at a hidden config page for LSW3 (http://LSW3IP/config_hide.html). There You can for instance set if LSW3 works in AP/STA mode or AP+STA mode.
I'd suggest setting AP/STA to use either one, not both.
On that page You can also turn off sending data outside (setting a bogus or loopback ip should do the trick).
