### ISSUE TITLE
Reading only 1 value

### ISSUE THREAD

**Issue by sibox1337** [MichaluxPL/Sofar_LSW3#52]
Hello, I got some chinese inverter INVT BD6TKL-RL1 and LSW3_15_840B_1.24 ( SN 234xxxxxxxxxxxx)
The problem is when i try to use the script it only gives me one single value and its -16143 ( b'\xa5\x13\x00\x10\x15\x00\x02\xe3\xa6~\x8b\x02\x01\x7fmQ7\xf6\n\x00\x00\xd8V\x03-\x01\x83\x02\xc0\xf1\xd8\x15' ) and i think its kind of error that i cannot understand? Can u please help

**Comment by MichaluxPL** [comment]
Response You get is much too short, so in fact You do not get any valuable data.
Unfortunately I don't know that inverter, so won't be able to help.
I'd suggest messing around with register addresses (best if You get it from the manufacturer), but there is no guarantee this script uses communication protocol suitable for Your inverter.

**Comment by sibox1337** [comment]
Can i test with single register only for example 0x0404 so when i receive some that to know where to look for?

**Comment by rimelis** [comment]
Each inverter has it's own table of registers. Even generations of the same model can differ a lot. For example Sofar Solar KTL-X G3 has absolutely different ranges than G2. You have very little chances to guess the right registers without documentation.
