### ISSUE TITLE
Support for DEYE SUN-8K-SG01LP1EU with LSW-3

### ISSUE THREAD

**Issue by reviscan** [MichaluxPL/Sofar_LSW3#53]
Hi I have a DEYE SUN-8K-SG01LP1EU and looking for a solution to read out the values. I got your script working. But needed to change a lot of registers. Do you mind if I clone your code and create a new one?

**Comment by pfostenberg** [comment]
I did not got a response so assume you are fine with that. https://github.com/pfostenberg/DeyeHI_LSW3_2Mqtt

**Comment by MichaluxPL** [comment]
> I did not got a response so assume you are fine with that. https://github.com/pfostenberg/DeyeHI_LSW3_2Mqtt

Sorry - I thought I've responded. Of course feel free to clone :)
