### ISSUE TITLE
inverter_sn=XXXXXXXXXX          # data logger S/N

### ISSUE THREAD

**Issue by ltspicer** [MichaluxPL/Sofar_LSW3#56]
Is

**Device information**
Device serial number: 2768...
Firmware version: LSW3_15_270A_1.68

the right serial?
My serial begins with 2768...
Work your script with this serial?

Output:
`Connecting to logger... connected successfully !
*** Chunk no:  0
Sent data:  bytearray(b'\xa5\x17\x00\x10E\x00\x001\x83\x08\xa5\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x03\x00\x00\x00(E\xd4\x00\x15')
Received data:  b'\xa5c\x00\x10\x15\x00\x151\x83\x08\xa5\x02\x013z\x05\x00\x80\x05\x00\x00\xeb\xc0/e\x01\x03P\x00\x03\xff\xc1\x05\x81\xff\xff\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00-\x00\x00\x00*\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x00\x00\x1d\x1f\xdd\x15'
0x0000 - Inverter status: "FAULT"
0x0001 - Fault 1: -63
0x0002 - Fault 2: 1409
0x0003 - Fault 3: -1
0x0004 - Fault 4: "ID50 Grid frequency sampling value between master and slave DSP vary widely"
0x0005 - Fault 5: "No error"
0x0006 - PV1 Voltage: 0.0V
0x0007 - PV1 Current: 0.0A
0x0008 - PV2 Voltage: 0.0V
0x0009 - PV2 Current: 0.0A
0x000A - PV1 Power: 0W
0x000B - PV2 Power: 0W
0x000C - Output active power: 0W
0x000D - Output reactive power: 0.0kVar
0x000E - Grid frequency: 0.0Hz
0x000F - L1 Voltage: 0.0V
0x0010 - L1 Current: 0.0A
0x0011 - L2 Voltage: 0.0V
0x0012 - L2 Current: 0.0A
0x0013 - L3 Voltage: 0.0V
0x0014 - L3 Current: 0.0A
0x0016 - Total production: 0kWh
0x0018 - Total generation time: 45h
0x0019 - Today production: 0Wh
0x001A - Today generation time: 42min
0x001B - Inverter module temperature: 0ºC
0x001C - Inverter inner termperature: 0ºC
0x001D - Inverter bus voltage: 0.0V
0x001E - PV1 voltage sample by slave CPU: 0.0V
0x001F - PV1 current sample by slave CPU: 0.0A
0x0020 - Countdown time: 50s
0x0021 - Inverter alert message: 0
0x0022 - Input mode: 0
0x0023 - Communication Board inner message: 0
0x0024 - Insulation of PV1+ to ground: 0
0x0025 - Insulation of PV2+ to ground: 0
0x0026 - Insulation of PV- to ground: 514
0x0027 - Country: "Germany"
`

**Comment by MichaluxPL** [comment]
You do not get the correct answer from the inverter.
Basing on the serial number I cannot say if will work or not.
If You set the correct registers number and despite it You do not get the correct answer, I guess it wont :(
